name: LenDen
version: 1.0.0

description: A new Flutter project for Lenden app.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: any
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  file_picker: ^10.2.0
  flutter_otp_text_field: ^1.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  string_similarity: ^2.1.1
  fl_chart: ^1.0.0
  socket_io_client: ^3.1.2
  flutter_slidable: ^4.0.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1
  device_info_plus: ^9.0.0
  pdf: ^3.11.3
  elegant_notification: ^2.0.0
  emoji_picker_flutter: ^4.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/Male.png
    - assets/Female.png
    - assets/Other.png
    - assets/icon.png

# flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
